name: carp_mobile_sensing_example
description: Examples of how to use the carp_mobile_sensing framework.
publish_to: 'none'
version: 0.40.9

environment:
  sdk: '>=3.1.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # carp_serializable:
  #   path: ../../carp_serializable/
  # carp_core:
  #   path: ../../carp_core
  carp_mobile_sensing:
    path: ../../carp_mobile_sensing/

flutter:
  uses-material-design: true
