name: carp_survey_package
description: CARP survey sampling package. Samples survey data from the Flutter Research Package.
version: 0.40.1
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/packages/carp_survey_package

environment:
  sdk: '>=3.1.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carp_serializable: ^1.0.0
  carp_core: ^0.40.0
  carp_mobile_sensing: ^0.40.0
  openmhealth_schemas: ^0.2.1
  research_package: ^1.2.0
  json_annotation: ^4.4.0
  permission_handler: ^10.0.0  


# Overriding carp libraries to use the local copy
# Remove this before release of package
dependency_overrides:
  # carp_core:
  #   path: ../../carp_core/
  # carp_mobile_sensing:
  #   path: ../../carp_mobile_sensing/
  # research_package: 
  #   path: ../../../../research.package
#  openmhealth_schemas:
#    path: ../../../openmhealth_schemas/

dev_dependencies:
  flutter_lints: any
  build_runner: any
  json_serializable: any
  test: any

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
