name: carp_webservices
description: Flutter API for accessing the CARP web services - authentication, file management, data points, and app-specific collections of documents.
version: 0.40.2
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/backends/carp_webservices

environment:
  sdk: '>=3.1.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carp_serializable: ^1.0.0
  carp_core: ^0.40.7
  carp_mobile_sensing: ^0.40.12  

  http: ^0.13.3
  http_parser: ^4.0.0
  uuid: ^3.0.4
  json_annotation: ^4.7.0
  retry: ^3.1.0
  meta: ^1.7.0
  form_field_validator: ^1.1.0
  url_launcher: ^6.0.9


# Overriding carp libraries to use the local copy
# Remove this before release of package
dependency_overrides:
  # carp_core:
  #   path: ../../carp_core/
  # carp_mobile_sensing:
  #   path: ../../carp_mobile_sensing/

dev_dependencies:
  build_runner: any
  json_serializable: any
  test: any

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - asset/images/

