name: carp_mobile_sensing
description: Mobile Sensing Framework for Flutter. A software framework for collecting sensor data from the phone and attached wearable devices via probes. Can be extended.
version: 0.40.13
homepage: https://github.com/cph-cachet/carp.sensing-flutter

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carp_serializable: ^1.0.0
  carp_core: ^0.40.7      # the core CARP domain model

  json_annotation: ^4.7.0
  system_info2: ^3.0.0
  uuid: ^3.0.4
  async: ^2.7.0
  path_provider: ^2.0.0
  sqflite: ^2.0.0                     # For local storage in SQLite DB
  archive: ^3.1.2
  permission_handler: ^10.0.0  
  shared_preferences: ^2.0.0
  package_info_plus: ^3.0.0
  flutter_local_notifications: ^13.0.0 # For sending notification on AppTask
  awesome_notifications: ^0.7.0       # For sending notification on AppTask
  cron: ^0.5.0                         # For scheduling / triggering cron jobs
  timezone: ^0.9.0
  stats: ^2.0.0                        # For calculating statistics, ex LightProbe
  flutter_native_timezone: ^2.0.0      # For getting local time zone for scheduling notifications

  # probe-dependent plugins
  device_info_plus: ^8.0.0
  sensors_plus: ^2.0.0
  battery_plus: ^3.0.0
  flutter_timezone: 1.0.0

  # the CACHET plugins
  pedometer: ^3.0.0       # Step count from local OS
  light: ^2.1.0           # Light sensor 
  screen_state: ^2.0.0    # Screen LOCK/ON/OFF

# Overriding carp core libraries to use the local copy
# Remove this before release of package
dependency_overrides:
  # carp_serializable:
  #   path: ../carp_serializable/
  # carp_core:
  #   path: ../carp_core/

dev_dependencies:
  build_runner: any
  json_serializable: any
  test: any
  flutter_lints: any

# The following section is specific to Flutter.
flutter:


# Useful pubspec commands:
#   flutter pub upgrade 
#   flutter pub outdated 
#   flutter pub outdated --no-dev-dependencies --up-to-date --no-dependency-overrides
#   flutter pub cache repair
#   ./gradlew clean
# 
# Auto generate json code (.g files) with:
#   flutter pub run build_runner build --delete-conflicting-outputs
